name: ci-goland-workflow
on: [push]
jobs:
    check-application:
        runs-on: ubutun-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2
            wuth:
                go-version: 1.15
            - run: go test
            - run go run match.go
